### ISSUE TITLE
【前端】問卷呈現切版

### ISSUE THREAD

**Issue by moluishere** [R-form/Rform#35]
+ 依照 google form 樣式進行切版
<img width="1410" alt="截圖 2022-05-03 下午5 04 30" src="https://user-images.githubusercontent.com/92732598/166430575-29c0b3c2-6e16-42c3-9629-a6d761a212c1.png">

**Comment by Kkrystalll** [comment]
![截圖 2022-05-06 上午11 01 53](https://user-images.githubusercontent.com/100756945/167059907-158e4c92-ce47-4569-a2ca-8fb5a9bf0229.png)
index.html.erb 頁面
- 可點擊卡片及顯示 show 畫面

待處理：
margin 部分點擊沒反應

預留：
tag 標籤位置
