### ISSUE TITLE
[後端]優化tag功能-part2

### ISSUE THREAD

**Issue by NikkaLin** [R-form/Rform#93]
1. 點擊icon之外的灰色部分也可以進入編輯輸入框
2. 使用套件設定調整輸入框大小
3. 包裝tag非編輯狀態
4. 每次變動皆自動存入

**Comment by moluishere** [comment]
可能也要加個自動儲存，目前只能靠 enter 跟點擊儲存

**Comment by Kkrystalll** [comment]
要加上讓畫面不跳轉嗎？
